version: '3.8'
services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  drupal_data:
    driver: local
  postgres_data:
    driver: local

