version: '3.8'
services:
  gogs:
    image: gogs/gogs
    ports:
      - "3000:3000"
      - "10022:22"
    volumes:
      - gogs_data:/data
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: gogs
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_gogs_data:/var/lib/postgresql/data

volumes:
  gogs_data:
    driver: local
  postgres_gogs_data:
    driver: local
